### ISSUE TITLE
Dodać konfiguracje dockera dla środowiska lokalnego/developerskiego

### ISSUE THREAD

**Issue by damian0o** [coding-tree/ctpanel-dev#1]
Po realizacji zadania developer nie musi posiadać upranień/hasła do połączenia do bazy w mongo cloud - moze własne mongo szybko postawić z użyciem docker/docker-compose

**Comment by z1gonzo** [comment]
Zakończono!

Now we can use Dockerized App!
We have MongoDB served locally.

Simple as never:
Install docker && docker-compose.
Run docker-compose build in root folder.
Run docker-compose up to start App!
